name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [main] # PR verification only (base=main)

jobs:
  # Build job for PR verification
  build:
    if: github.event_name == 'pull_request'
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/actions/python-init
      - name: Build sdist and wheel
        run: uv build
      - uses: ./github/actions/python-post
