name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/python-init

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest tests

      - uses: ./.github/actions/python-post
