name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/python-init

      - name: Build MkDocs site
        run: uv run mkdocs build -f mkdocs/mkdocs.yaml

      - uses: ./.github/actions/python-post
