name: Publish docs to GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    # on change to watched file(s)
    branches: [main]
    paths:
      - mkdocs/**
      - mkdocs_external_files/**
      - usajobsapi/**/*.py
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:
    branches: [main] # PR verification only (base=main)
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  # Build job for PR verification
  build:
    if: github.event_name == 'pull_request'
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/python-init

      - name: Build MkDocs site
        run: uv run mkdocs build -f mkdocs/mkdocs.yaml

      - uses: ./.github/actions/python-post

  publish:
    # on release or push to main
    if: >-
      github.repository == 'paddy74/python-usajobsapi' &&
      (
        (
          github.event_name == 'release' &&
          github.event.release.prerelease == false &&
          github.event.release.draft == false
        ) ||
        (
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        )
      )
    name: Publish docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: true

      - name: Check out branch
        if: github.event_name != 'release'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: ./.github/actions/python-init

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force --clean --config-file mkdocs/mkdocs.yaml --remote-branch gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/python-post
