name: Publish docs to GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    # on change to watched file(s)
    branches: [main]
    paths:
      - mkdocs/**
      - mkdocs_external_files/**
      - usajobsapi/**/*.py
      - README.md
      - CHANGELOG.md
      - LICENSE
  pull_request:
    branches: [main] # PR verification only (base=main)
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag, or SHA to deploy"
        required: false
        default: ""

permissions:
  contents: read

jobs:
  # Build job for PR verification
  build:
    if: github.event_name == 'pull_request'
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/python-init

      - name: Build MkDocs site
        run: uv run mkdocs build -f mkdocs/mkdocs.yaml

      - uses: ./.github/actions/python-post

  publish:
    # on release, push to main, or manual dispatch
    if: >-
      github.repository == 'paddy74/python-usajobsapi' &&
      (
        (
          github.event_name == 'release' &&
          github.event.release.prerelease == false &&
          github.event.release.draft == false
        ) ||
        (
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        ) ||
        github.event_name == 'workflow_dispatch'
      )
    name: Publish docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out release tag
        if: github.event_name == 'release'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: true

      - name: Check out branch
        if: github.event_name == 'push'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve dispatch ref
        if: github.event_name == 'workflow_dispatch'
        id: dispatch-ref
        run: |
          ref="$DISPATCH_REF"
          if [ -z "$ref" ]; then
            if [ -n "$GITHUB_REF" ]; then
              ref="$GITHUB_REF"
            else
              ref="$GITHUB_SHA"
            fi
          fi
          echo "ref=$ref" >> "$GITHUB_OUTPUT"
        env:
          DISPATCH_REF: ${{ github.event.inputs.ref }}
      - name: Check out dispatch ref
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ steps.dispatch-ref.outputs.ref }}
          persist-credentials: true

      - uses: ./.github/actions/python-init

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force --clean --config-file mkdocs/mkdocs.yaml --remote-branch gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/python-post
