site_name: python-usajobsapi
site_url: https://python-usajobsapi.github.io/
site_description: Project documentation for python-usajobsapi

site_dir: ../site

repo_url: https://github.com/paddy74/python-usajobsapi/
edit_uri: blob/master/docs/

theme:
  name: readthedocs
  locale: en
  highlightjs: true

nav:
  - Home: index.md
  - Reference:
      - __init__.py: ref/__init__.md
      - _version.py: ref/_version.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md

plugins:
  - search
  - gen-files:
      scripts:
        - gen_ref_pages.py
  - mkdocstrings
  - external-files:
      files:
        - src: ../README.md
          dest: README.md
        - src: ../CHANGELOG.md
          dest: about/changelog.md
        - src: ../LICENSE
          dest: about/license.md

markdown_extensions:
  - toc:
      baselevel: 2

hooks:
  - hooks.py

watch:
  - ../usajobsapi/_version.py
